hubot:
  build: .
  environment:
    - HUBOT_SLACK_TOKEN
    - SLACK_TIMELINE_MSG_REDIS
    - SLACK_LINK_NAMES
    - SLACK_UNFURL_LINKS
    - SLACK_UNFURL_MEDIA
    - SLACK_TIMELINE_CHANNEL
    - SLACK_TIMELINE_RANKING_ENABLED
    - SLACK_TIMELINE_RANKING_CHANNEL
    - SLACK_TIMELINE_RANKING_CRONJOB
    - SLACK_TIMELINE_RANKING_TOP_N
    - TZ
    - HUBOT_LOG_LEVEL
  ports:
    - "8080:8080"
  restart: always
